In [6]:
import pandas as pd

In [9]:
clf = pd.read_excel("G:\\Meu Drive\\API_5Sem\\API5Doc\\Power BI\\treinamento_dt_vendedor.xlsx")

In [65]:
clf.head()

             cnpj  estado     cnae  nat  idade  cons_mes
0  32050925000133      21  4784900  213      4         2
1  33843223000170      23  4929902  213      4         2
2  23179421000127      18  4771703  213      8         4
3  24071384000100      18  4781400  230      7         1
4  30916964000145      19  7319003  213      5         4

In [59]:
inputs = clf.drop(['cnpj','cons_mes'], axis='columns')
target= clf['cons_mes']

In [60]:
inputs.head(n=5)

   estado     cnae  nat  idade
0      21  4784900  213      4
1      23  4929902  213      4
2      18  4771703  213      8
3      18  4781400  230      7
4      19  7319003  213      5

In [66]:
inputs.shape

(1497, 4)

In [61]:
from sklearn import tree

In [62]:
class_venda = tree.DecisionTreeClassifier()

In [63]:
class_venda.fit(inputs,target)

DecisionTreeClassifier()

In [64]:
class_venda.score(inputs,target)

0.6673346693386774

In [67]:
class_venda.predict([[1,1414200,213,29],[1,1531902,206,29],[2,1531902,213,29],[2,810007,206,40],[2,9329899,213,28],[2,9329899,399,28],[2,9420100,206,28],[3,9430800,206,28],[3,9430800,213,27],[3,9430800,213,27],[3,9430800,213,27],[4,9492800,308,27],[5,9492800,206,38],[5,9492800,206,26],[5,9492800,206,26],[5,9499500,213,26],[5,9499500,206,26],[5,9511800,213,26],[5,9511800,399,26],[5,9511800,206,25],[5,9511800,206,25],[5,9521500,213,25],[5,9521500,213,25],[5,9601701,206,18],[5,9602501,213,25],[5,9602501,308,25],[5,9602501,213,24],[5,9602501,399,24],[5,9602501,213,24],[5,9602501,213,37],[6,9602501,206,24],[6,9602501,213,24],[6,9602501,230,24],[6,9602502,213,24],[6,9602502,206,24],[6,9602502,308,24],[6,9602502,213,24],[6,9603304,213,24],[6,161001,213,24],[6,161003,206,24],[6,162899,206,24],[6,1052000,206,24],[6,2592602,206,23],[6,4634601,399,23],[6,4639701,213,23],[6,4222701,206,23],[6,4321500,206,23],[7,4322301,206,23],[7,4322302,213,23],[7,4330402,213,23],[7,4330404,206,22],[7,4330404,213,23],[7,9609299,206,22],[7,9700500,213,22],[7,9700500,213,19],[7,2099199,206,22],[7,2219600,213,22],[7,3101200,213,22],[7,3101200,206,22],[8,3212400,213,22],[8,4644301,206,22],[8,4330405,206,38],[8,4330499,206,21],[8,4399103,206,21],[8,4399103,206,22],[8,4399103,206,21],[8,4399103,213,21],[8,4399103,313,21],[8,4399103,206,21],[8,4511102,206,21],[9,4511102,308,20],[9,4520001,206,20],[9,4520001,399,20],[9,4520002,206,20],[9,4520005,308,19],[9,4530701,213,19],[9,3319800,230,19],[9,3600602,206,18],[9,4663000,213,18],[9,4530703,206,18],[9,4615000,206,18],[9,4616800,230,17],[10,2330302,206,15],[10,1340501,213,17],[10,1411801,213,17],[10,1411802,206,17],[10,1412601,213,15],[10,1412602,206,16],[11,8112500,213,16],[11,8112500,206,16],[11,8112500,206,16],[11,8112500,206,16],[11,8112500,213,16],[11,8112500,213,16],[11,3299002,206,38],[11,3299003,213,15],[11,3299099,399,14],[11,3299099,206,14],[11,3299099,206,14],[11,3811400,213,13],[11,3839499,213,13],[11,4120400,206,13],[11,4120400,224,13],[11,4120400,206,36],[11,4120400,213,13],[11,4712100,213,13],[11,4712100,222,13],[11,4712100,213,13],[11,4712100,206,11],[11,4712100,230,13],[11,4712100,213,13],[11,4712100,399,12],[11,4712100,206,12],[11,4713002,213,12],[11,4721103,206,12],[11,4721104,213,12],[11,4721104,213,12],[11,4722901,213,12],[11,4722901,213,12],[11,4723700,213,12],[11,4723700,230,12],[11,4723700,213,12],[12,4723700,206,12],[12,4723700,213,12],[12,4723700,213,12],[12,4724500,213,12],[12,4724500,213,12],[13,4724500,213,12],[13,4729699,213,12],[13,4729699,399,12],[13,4741500,213,12],[13,4742300,213,11],[13,4742300,213,11],[13,4742300,213,11],[13,4743100,213,11],[13,4744001,327,12],[14,4744002,213,11],[14,4744005,213,43],[14,4744005,206,11],[14,4753900,213,11],[15,4753900,213,11],[15,4754701,213,11],[15,4754701,213,11],[15,5223100,206,11],[15,5229002,213,11],[16,6470101,213,10],[16,8129000,213,10],[16,8219999,213,10],[16,8230001,206,10],[16,8230001,213,10],[16,8230002,213,10],[16,8230002,213,10],[16,8291100,213,10],[16,8299799,213,10],[16,8299799,213,10],[16,8512100,213,10],[16,8513900,213,10],[16,8513900,213,10],[16,4619200,213,10],[16,4619200,213,10],[16,4623102,213,10],[16,4623108,213,10],[16,4631100,213,9],[16,4755502,213,9],[16,4755502,213,9],[17,4755502,213,9],[17,4755502,213,9],[17,4755503,213,9],[17,4755503,213,9],[17,4759899,213,9],[18,4761003,213,9],[18,4761003,213,9],[18,4761003,213,9],[18,4763603,213,9],[18,4771701,213,9],[18,4771701,213,9],[18,4771701,206,9],[18,4772500,213,9],[18,4772500,213,9],[18,4772500,213,8],[18,4774100,213,8],[18,4774100,213,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,206,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,206,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,213,8],[18,4781400,206,8],[18,4781400,213,8],[18,4781400,230,8],[18,4781400,223,8],[18,4781400,213,8],[18,4781400,213,8],[18,4782201,213,8],[19,4782201,206,8],[19,4782202,230,8],[19,5320202,206,8],[19,5510801,213,8],[19,5510801,213,8],[19,5510801,206,34],[19,5510801,213,8],[19,5611201,213,8],[19,5611201,213,8],[19,5611201,213,8],[19,5611201,213,8],[19,5611201,213,7],[19,5611201,213,7],[19,5611201,213,7],[19,5611203,206,7],[19,5611203,213,7],[19,5611203,213,7],[19,5611203,213,7],[19,5611203,213,7],[19,5612100,213,7],[19,5612100,213,7],[19,5612100,213,7],[19,5620102,401,33],[19,5620102,213,7],[19,5620104,213,7],[19,5620104,213,7],[19,5819100,213,7],[19,5829800,206,34],[19,6622300,409,7],[19,6622300,409,7],[19,6810202,409,7],[20,6821802,213,6],[20,6911701,213,6],[20,6911701,213,6],[20,6920601,213,6],[20,7111100,213,6],[20,7112000,213,6],[20,7319002,213,6],[21,7319003,213,6],[21,8599601,213,6],[21,8599601,213,6],[21,8599604,213,6],[22,8599604,213,6],[22,8599699,206,6],[22,8630503,213,5],[22,9313100,213,5],[22,9313100,213,5],[22,4783101,213,5],[22,4783101,213,38],[22,4789001,213,5],[22,4789005,213,5],[22,4789005,213,5],[22,4789099,213,5],[22,4789099,213,5],[22,4789099,206,4],[22,4789099,206,4],[22,4923001,213,4],[22,4923001,213,4],[22,6209100,213,4],[22,7319099,213,4],[22,7420004,213,4],[22,7711000,213,4],[22,7722500,213,4],[22,4924800,213,4],[22,4929901,213,4],[22,4929901,206,4],[22,4929904,206,4],[22,4930201,213,4],[22,4930202,213,4],[22,4930202,213,4],[22,4930202,213,4],[22,7739003,232,4],[22,9001901,213,4],[22,4751201,213,4],[22,1091101,213,4],[22,1091102,213,34],[23,1091102,206,4],[23,1091102,213,4],[23,7410299,213,4],[23,2399101,206,31],[23,2399101,213,3],[23,2421100,206,32],[23,2392300,206,31],[23,2421100,213,49],[23,2421100,213,30],[23,2399101,401,30],[23,2423702,308,29],[23,2421100,206,29],[23,2421100,213,28],[23,2442300,206,29],[23,2423702,206,30],[23,2442300,213,34],[23,2442300,206,34],[24,2423702,206,34],[24,2399101,213,17],[24,2392300,206,40],[25,2442300,206,38]]
)

array([3, 4, 1, 4, 2, 1, 2, 4, 3, 3, 3, 1, 4, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 4, 2, 4, 1, 1, 1, 3, 3, 1, 1, 1, 3, 4, 1, 1, 3, 1, 3, 3, 2, 3,
       3, 2, 2, 4, 3, 1, 4, 1, 1, 2, 2, 3, 1, 3, 3, 2, 4, 1, 1, 3, 3, 3,
       1, 4, 3, 4, 4, 4, 2, 4, 4, 4, 3, 2, 2, 4, 2, 2, 3, 3, 3, 2, 3, 2,
       3, 1, 1, 1, 3, 3, 2, 1, 2, 2, 2, 4, 4, 4, 4, 2, 4, 3, 3, 3, 1, 3,
       3, 2, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 4, 4, 2, 4, 4,
       4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 3, 2, 4, 4, 1, 4,
       4, 2, 3, 3, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 1, 3, 3, 3, 4, 1, 1,
       2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4,
       2, 2, 4, 4, 1, 2, 3, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2,
       2, 2, 4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       1, 1, 1, 1, 3, 1, 2, 2, 3, 1, 4, 2, 2, 2, 2, 3, 3, 2, 2, 1, 3, 1,
       4, 3, 2, 3, 2, 2, 3, 3, 3, 3, 2, 1, 1, 3, 3, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)